#!/bin/bash

# List all network interfaces based on OS
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    interfaces=($(ls /sys/class/net))
elif [[ "$OSTYPE" == "darwin"* ]]; then
    interfaces=($(ifconfig -u | awk '/^[a-z0-9]/ {print $1}'))
else
    echo "Unsupported OS"
    exit 1
fi

# Display the interfaces with numbers
echo "Available network interfaces:"
for i in "${!interfaces[@]}"; do
    echo "$i: ${interfaces[$i]}"
done

# Prompt the user to choose an interface
read -p "Enter the number of the network interface: " num

# Fetch and display the IP address of the chosen interface
interface=${interfaces[$num]}
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Linux
    ip -4 addr show $interface | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    ifconfig $interface | grep "inet " | awk '{print $2}'
else
    echo "Unsupported OS"
fi

