#!/usr/bin/env bash

main() {
  read -p "Enter host entry to update: " HOST_ENTRY
  update_host "$HOST_ENTRY"
}

get_host_ip() {
  awk "/$1/{print \$1; exit}" /etc/hosts
}

update_host() {
  local OLD_IP=$(get_host_ip "$1")
  if [[ -z "$OLD_IP" ]]; then
    echo "Error: Host entry '$1' does not exist."
    exit 1
  fi

  if [[ "$EUID" -ne 0 ]]; then
    echo "Error: This script requires sudo privileges"
    if sudo -v; then
      sudo "$0" "$HOST_ENTRY"
    else
      echo "Please run with sudo."
    fi
    exit
  fi

  read -p "Enter new IP for $1: " NEW_IP
  sudo sed -i "/$OLD_IP[[:space:]]\+$1/c\\$NEW_IP $1" /etc/hosts
}

main "$@"
